### ISSUE TITLE
db_mysql does not allow for innodb_log_file_size changes from restore

### ISSUE THREAD

**Issue by EricByers** [flexera-public/rightscale_cookbooks#166]
Currently when a restore happens, there is a cleanup task that happens in db_mysql/providers/default.rb called ':post_restore_cleanup'.  

This eventually calls db_mysql_set_mycnf, which updates the server_id/relay_log/innodb_log_file_size so that MySQL can start with the correct log file size (without the correct on MySQL will fail to start).  This is required if the log file size is different on the backup.

However it uses 'RightScale::Database::MySQL::Helper' to get the uuid/relay data, which when it inits in turn creates the db connection, and attempts to start the database.  Because the my.cnf has not been written out yet it fails (Essentially a hard dependency on starting the database to get the uuid to fix it so it can start).

Going from the v12 MySQL 5.1 to v13 MySQL 5.5 currently cannot upgrade because the default log file size changed, and this recipe appears to be broken.

Let me know if i can provide any additional information or details.

**Comment by douglaswth** [comment]
If you are having a problem with our v13.5.X LTS ServerTemplates please contact RightScale Support.

**Comment by EricByers** [comment]
I have, and I documented it here for others experiencing the same issue so they could understand there is a (potential) bug here and have something to go off of.

I saw the issues tab, and I was trying to be helpful in reporting this.  Sorry if that was incorrect.

**Comment by lopaka** [comment]
This issue is recreated when 2 conditions are met:
- restoring a MySQL 5.1 database in MySQL 5.5, which triggers running `mysql_upgrade`, and
- having a different innodb_log_file_size on the restored database from the auto-tuning

A solution for this issue has been developed for the db_mysql cookbook and is currently under internal review and QA.

Closing issue since a RightScale Support ticket has been filed.
